# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e99c2b176b1673cf3b620548d3e2b485da41ca293940aaae3eba79e5c49b3d3c6e11167dc6dd71c3c9c371b37cfe321b665f37ef1377830d6d73a8897503c654

test:
  secret_key_base: 98e0ea92caf1eeda699166438db8ee1eb3707f6409e66dc6b77767941d4a373bb8131aea6bbe7c43fde6c1f08d5e306bab76da591ac4b24a609b04e763a4d9e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
